### PR TITLE
Add Maven 3.9.0 to the build matrix

### PR DESCRIPTION
**Pull request by TimMoore**
Replaces #79 which for some reason did not update to include my second commit on the branch.

### CODE REVIEW

**Comment by TimMoore** [comment]
The build is failing with 4.0.0-alpha-4, and the error isn't very obvious to me. I'm not across the changes in 4.0. I should have guessed it wouldn't be so easy. I don't think getting this to work with the alpha version of Maven 4.0 should block testing with the released Maven 3.9.0, so I'll revert that change and make it a separate issue to support 4.0.0.

**Comment by olamy** [comment]
well ideally you could stop using this setup maven :) and add a step to setup `mvnw` such `mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.1.0:wrapper "-Dmaven=${{ matrix.maven }}"`

**Comment by TimMoore** [comment]
I'll plan to merge after 16 February 2023 at 00:00 UTC unless there's an objection before then.

**Comment by olamy** [comment]
just see as well you could remove the cache part as it's now part of the setup java action ;)

**Comment by olamy** [comment]
I can have a try if you need help

**Comment by TimMoore** [comment]
> well ideally you could stop using this setup maven :) and add a step to setup `mvnw` such `mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.1.0:wrapper "-Dmaven=${{ matrix.maven }}"`

I was just thinking the same thing. It should also make it easier to test with different Maven versions locally. Raised as #84.

> I can have a try if you need help

That would be great @olamy. Thanks!

**Comment by TimMoore** [comment]
Maybe this can be merged straight away, then. It shouldn't be controversial.

**Pull request merged**
